# Data transformation

In order to convert the data into the form we need for further analysis, we do the following steps:

**1) We remove these two types of columns in the dataset:**  

[1] Columns not used in our research: `Reference Period Code`, `Reference Period`, `Flag Codes` and `Flags`  

[2] Repeated columns which only explain the previous columns in details: `Financing scheme` (explain `HF`), `Function` (explain `HC`), `Provider` (explain `HP`), `Measure` (explain `MEASURE`), `Country` (explain `LOCATION`), `Year` (explain `TIME`), `Unit` (explain `Unit Code`) and `PowerCode` (explain `PowerCode Code`)

**2) We only preserve data of these 12 countries,** Brazil (BRA), Canada (CAN), Chili (CHL), Germany (DEU), France (FRA), the United Kingdom (GBR), Iceland (ISL), Mexico (MEX), Poland (POL), Russia (RUS), Turkey (TUR) and the United States (USA).

**3) We add a new column `TYPE` to classify these 12 countries into developing and developed countries.** 

(Reference website: https://en.wikipedia.org/wiki/Developed_country)  

Developed countries: Canada (CAN), Germany (DEU), France (FRA), the United Kingdom (GBR), Iceland (ISL), the United States (USA)  

Developing countries: Brazil (BRA), Chili (CHL), Mexico (MEX), Poland (POL), Russia (RUS), Turkey (TUR)

**4) We only keep the data calculated within all financing schemes by selecting "HFTOT" in `HF`.**

