# Conclusion

In this project, we focus on analyzing the health expenditure of various countries over time. After processing and transforming data, and creating visualizations with data, we have a deeper and more comprehensive understanding of healthcare expense. The main conclusions and explorations are listed below.

## Total health expenditure

Total health expenses and total health expenses per capita of all 12 countries kept increasing from 2010 to 2019, while the trend in ratio of total health expenditure to GDP varied among countries. Compared with developing countries, the total health expenditure of developed countries grew more slowly and stably; the expenditure per capita and the ratio of expenditure to GDP was much higher; the trend in ratio of expenditure all fluctuating little around a certain value. Moreover, the United States was much higher on both total health expenditure per capita and the ratio of total health expenditure to GDP than other countries.

**To sum up,** as time goes on, people in all countries tend to spend more on health. What's more, people in developed countries, especially in the United States, attach more importance on health issues than developing countries. The ratio of total health expenditure to GDP of developed countries tend to be stable and might not changed abruptly.

## Expenditure on different medical products and services

Among all kinds of medical products and services, the inpatient curative and rehabilitative care and outpatient curative and rehabilitative care account for the largest proportions of total health expenditure, followed by medical goods and long term care. Compared with developed countries, developing countries expended more on inpatient curative and rehabilitative care, ancillary services and medical goods, less on long term care and governance and health system and financing administration. Moreover, Russia spent much more on inpatient curative, and the United States expended much more on outpatient curative than other countries.

**In a word,** inpatient and outpatient curative and rehabilitative care take up majority in all countries, especially in Russia and the United States. In addition, People in developing countries pay less attention to long term care than people in developed countries. Due to less expense on this aspect, developing countries might have a health system with less efficiency and poor administration.


## Expenditure on different organizations and actors that deliver health care goods and services

Most of health expenditures were concentrated on hospitals, providers of ambulatory health care, followed by retailers and other providers of medical goods. As for expenses on hospital, Poland kept growing, while Germany kept descending as time passes by; compared with developing countries, developed countries tend to first increased and then decreased. Also, there might be a positive relationship between expenditure on providers of ambulatory health care and health care system administration and financing, and between providers of medical goods and preventive care.

**On the whole,** people in all countries tend to go to health care facilities for consultation or treatment, rather than purchase medicines in pharmacies or retail stores, while people in developed countries turned to buy medicines directly in recent years. Furthermore, expenditure on treatment of day-cases and home care services may be positively correlated with that on regulation and administration on health care agencies, as well as expenditure on medical stuff in drugstores and that on prevention care.